package org.eclipse.scout.demo.wrappedform.shared.ui.forms;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@ClassId("e23dbb9b-3cf6-40da-8baa-065ab7f9f8d6-formdata")
@Generated(value = "org.eclipse.scout.demo.wrappedform.client.ui.forms.AbstractDetachableForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractDetachableFormData extends AbstractFormData {

	private static final long serialVersionUID = 1L;

	public AbstractDetachableFormData() {
	}
}
