package org.eclipse.scout.demo.wrappedform.shared.ui.forms;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@ClassId("e55cf14b-8005-42d4-a54d-4fedf7ebec88-formdata")
@Generated(value = "org.eclipse.scout.demo.wrappedform.client.ui.forms.WrappedFormFieldForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class WrappedFormFieldFormData extends AbstractFormData {

	private static final long serialVersionUID = 1L;

	public WrappedFormFieldFormData() {
	}
}
